### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by Almadani92** [RussellSB/automated-gait-analysis#2]

**Comment by Almadani92** [comment]
Could you please provide the dependencies of the project. This is because I am facing problem in installing mxnet package with gpu. I am using ubuntu18 with cuda-10.2 and cudnn v7 and still facing an issue.
In another word, which cudnn version you used in this project?

Thanks a lot in advance.

**Comment by RussellSB** [comment]
Hi Almadani!

I've done this project quite a while ago, before I was familiar with writing good tutorial-esque READMEs! Excuse the lack of clarity.

I'm not sure what version I used, (nor can I check since I no longer have the same environment) but if you'd like to use cpu for the time being it's possible.

The pose estimation part doesn't even support GPU at the time that I did this. Was only using GPU for the YOLO part.

This worked for another person having gpu issues. Go to pose_estimstion.py. Install CPU mxnet. Remove line 29, edit line 30 to not have the ctx argument.
